Update "action name" update_address_group.yaml
StackStorm-Exchange/stackstorm-fortinet pull request #6
Opened 2019-10-11 15:51 UTC by blourdel

The "action name" is wrong leading to duplicate "action name" at pack install time.
The new action name is : update_address_group_object, reflection the actual action purpose and content

2019-10-11 17:29 UTC, armab commented on actions/update_address_group.yaml
> +name: update_address_group_object
Indeed, there is another action with the same name 

https://github.com/StackStorm-Exchange/stackstorm-fortinet/blob/01d477824b4dbf5a635d028a2663ae87f086a314/actions/update_address_object.yaml#L1-L4

2019-10-11 17:30 UTC, arm4b requested changes
Thanks for the contribution! The fix looks good. :+1: 

Please update the CHANGELOG and increment pack version to make sure we'll be able to release it.

2019-10-14 06:12 UTC, blourdel commented
pack.yaml and CHANGEs.md files updated to prepare a publishable new version.

2019-10-14 19:51 UTC, arm4b approved these changes
:+1: 

Thanks for the fix!

2019-10-14 19:51 UTC, merged